set nocompatible

" Plugins
call plug#begin()
call plug#end()

filetype plugin indent on
syntax on
set encoding=utf-8

" Appearance
set number
set relativenumber
highlight LineNr ctermfg=grey guifg=#888888
highlight CursorLineNr ctermfg=grey guifg=#888888
set scrolloff=8

" Indentation
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" Behavior
set hidden
set nowrap
set splitbelow
set splitright
set backspace=indent,eol,start
set wildmenu
set wildmode=longest:full,full

" Persist undo
set undofile
set undodir=~/.vim/undodir

" Cursor shape per mode (fixes bar cursor inherited from neovim/terminal)                                                                                       │
let &t_SI = "\e[6 q"   " INSERT: vertical bar                                                                                                                   │
let &t_EI = "\e[2 q"   " NORMAL: solid block                                                                                                                    │
let &t_SR = "\e[4 q"   " REPLACE: underline                                                                                                                     │
let &t_ti .= "\e[2 q"  " block on vim entry                                                                                                                     │
let &t_te .= "\e[0 q"  " reset cursor on vim exit

" which-key
set timeoutlen=500
