-- neotest is disabled; uncomment vim.pack.add calls and setup to enable
-- vim.pack.add("https://github.com/sidlatau/neotest-dart")
-- vim.pack.add("https://github.com/nvim-neotest/neotest-python")
-- vim.pack.add("https://github.com/nvim-neotest/neotest")
--
-- require("neotest").setup({
--   adapters = {
--     require("neotest-dart")({
--       command = "flutter",
--       use_lsp = true,
--     }),
--     require("neotest-python"),
--   },
--   log_level = vim.log.levels.WARN,
--   timeout = 30000,
--   output_panel = {
--     open_on_run = true,
--   },
--   consumers = {
--     live_output = function(client)
--       client.listeners.run = function(_, _)
--         require("neotest").output_panel.clear()
--       end
--     end,
--   },
--   output = {
--     enabled = true,
--     open_on_run = "short",
--   },
--   quickfix = {
--     enabled = false,
--   },
-- })
--
-- local map = vim.keymap.set
-- map("n", "<leader>tt", function() vim.cmd("wa"); require("neotest").run.run() end, { desc = "Run nearest test" })
-- map("n", "<leader>tf", function() vim.cmd("wa"); require("neotest").run.run(vim.fn.expand("%")) end, { desc = "Run file tests" })
-- map("n", "<leader>ts", function() require("neotest").summary.toggle() end, { desc = "Toggle test summary" })
-- map("n", "<leader>to", function() require("neotest").output_panel.toggle() end, { desc = "Toggle test output" })
-- map("n", "<leader>ta", function() vim.cmd("wa"); require("neotest").run.run(vim.fn.getcwd()) end, { desc = "Run all tests" })
-- map("n", "<leader>tO", function() require("neotest").output.open({ enter = true }) end, { desc = "Show test output" })
-- map("n", "<leader>tl", function() vim.cmd("wa"); require("neotest").run.run_last() end, { desc = "Run last test" })
